### ISSUE TITLE
pp on hash tag on  I'm a possumPrivacy Possum ENABLED Blocked tracking headers:      referer headers blocked from 8 sources      https://dev.appboy.com/api/v3/data/  Report a bug

### ISSUE THREAD

**Issue by usernamealreadyis** [cowlicks/privacypossum#102]
If you are reporting a bug, then providing the following is helpful:
* browser name and version
* privacy possum version

If a website is broken, please provide the URL and describe the problem.

If you would like to be extra helpful, and know how to access the Javascript console for the extension, please provide a debug log. The debug log may contain information about your browsing, such as URLS. Please read through it and redact information as you see fit.

You can access the debug log from the popup console by running `popup.debug()`, or from the extension's background page by running ``possum.prettyLog(Privacy Possum
ENABLED
Blocked tracking headers:

    referer headers blocked from 15 sources
    cookie headers blocked from 4 sources

Report a bug `)`.`
I'm a possumPrivacy Possum
ENABLED
Blocked tracking headers:

    referer headers blocked from 9 sources
    etag headers blocked from 1 sources
    cookie headers blocked from 1 sources

> any resolution on this issue? getting same problem on Windows 10, after running npm install @angular/cli -g getting ng not recognized.

C:\Users\sh062v>npm install @angular/cli -g
C:\Users\sh062v\AppData\Roaming\npm\ng -> C:\Users\sh062v\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng£
I'm a possumPrivacy Possum
ENABLED
Blocked tracking headers:

    referer headers blocked from 49 sources
    cookie headers blocked from 19 sources

    https://dev.appboy.com/api/v3/data/

Report a bug

> @angular/cli@6.0.0 postinstall C:\Users\sh062v\AppData\Roaming\npm\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@6.0.0
updated 1 package in 18.699s

Report a bug
`

**Comment by cowlicks** [comment]
Closing re #107
