### ISSUE TITLE
C:\Users\M6006\Desktop\8faf0ecba2f71efb31a86c3d42924681.jpg

### ISSUE THREAD

**Issue by Michaelpad** [cowlicks/privacypossum#106]
If you are reporting a bug, then providing the following is helpful:
* browser name and version
* privacy possum version

If a website is broken, please provide the URL and describe the problem.

If you would like to be extra helpful, and know how to access the Javascript console for the extension, please provide a debug log. The debug log may contain information about your browsing, such as URLS. Please read through it and redact information as you see fit.

You can access the debug log from the popup console by running `popup.debug()`, or from the extension's background page by running `possum.prettyLog()`.

**Comment by cowlicks** [comment]
Hi @Michaelpad I think your comment is a clue that I've made making bug reports too difficult. I'm closing this, and creating a separate issue for making bug reports simple. If you read this, leave a comment below describing your issue and we can figure it out from there.

Thanks,
