### ISSUE TITLE
Breaks DuckDuckGo

### ISSUE THREAD

**Issue by ShintoPlasm** [cowlicks/privacypossum#11]
PP seems to break DuckDuckGo in my Firefox installation (Stable 59.0.2, macOS) - when the extension is enabled (both when enabled or disabled for duckduckgo.com) all I'm getting is a blank page with the DDG logo and search box, but no results. When I disable the extension, all is back to normal. Please see the attached screen grab - the 'Google it' button comes from the DuckDuckGoogle extension, but I'm getting a similar page when this other extension is disabled.
<img width="1162" alt="screen shot 2018-05-07 at 08 07 54" src="https://user-images.githubusercontent.com/35544416/39687250-c5a7c2b2-51cd-11e8-879b-93df1774a55f.png">

**Comment by cowlicks** [comment]
@ShintoPlasm Hi! First thank you for your patience while we deal with the first big wave of installs Privacy Possum has gotten. I actually surprised that more didn't break.

I fixed a released a patch for this today in 15db4394af 

I'll be adding selenium tests on Travis-ci soon so we can test for stuff like this automatically. See #7
