### ISSUE TITLE
privacypossum vs privacybadger

### ISSUE THREAD

**Issue by rhetr** [cowlicks/privacypossum#113]
if privacy possum is based on privacy badger, is there any benefit in using both, or will privacy possum do the same and more?

**Comment by cowlicks** [comment]
Privacy Possum is **not** based on privacy badger, it is written completely from scratch. We only use some data from the privacy badger repository (the multi-domain first party list). Privacy Possum uses a different set of heuristics so whatever benefits each provide should add together fine. If you have any problems using both, please let me know.

I'm closing this issue. If you have any more questions, feel free to reopen it. Or create a new issue.
