### ISSUE TITLE
Request option to toggle PP icon colour for use with darker themes.

### ISSUE THREAD

**Issue by Gl4nza** [cowlicks/privacypossum#121]
Hi, would it be possible for the icon to have an option for a lighter colour, compared to other icons PP gets lost when used with darker themes.

Example below showing PP icon when used with Arc theme on Firefox.

Thanks.

![image](https://user-images.githubusercontent.com/43491414/45914829-77184b80-be42-11e8-8cde-549a68c4bf8f.png)

**Comment by cowlicks** [comment]
Hello @Gl4nza thank you for reporting this! Someone has already reported it as issue #46 so I'm closing this in favor of that.
