### ISSUE TITLE
Break vbulletin answering even when disabled for the website

### ISSUE THREAD

**Issue by MikeZeDev** [cowlicks/privacypossum#16]
If i disable the extension completely it works

TypeError: line.match(...) is null[En savoir plus]
fingercounting.js:45:10
TypeError: vBobjects is undefined[En savoir plus]
vbulletin_global.js:55:20
TypeError: vBobjects is undefined[En savoir plus]

**Comment by cowlicks** [comment]
Hi @MikeZeDev can you link me to a vbulletin istall where this occurs?

**Comment by MikeZeDev** [comment]
Sorry i can't , the website is private. 
Anyway, i've just updated the addon, and the issue is fixed.

Whitelisted or not, its working as intended, this issue can be closed.

Thanks for that !
