### ISSUE TITLE
Breaks Mega.nz even when whitelisted

### ISSUE THREAD

**Issue by MikeZeDev** [cowlicks/privacypossum#17]
Same problem than with vbulletin based forums. Disabling the extension fixed it.

I guess "whitelisting a website" doesnt prevent all modifications by this addon.

**Comment by mazesy** [comment]
> I guess "whitelisting a website" doesnt prevent all mofidications by this addon.

Indeed. And that is truly problematic.

**Comment by cowlicks** [comment]
Hi @MikeZeDev @mazesy  , thank you for your report! I've submitted a fix for the DDG and Qwant breakages. Can you please let me know what other sites are broken? I'd like to fix them.

I fixed the issue that was occurring on mega.nz this morning and made a release. See https://github.com/cowlicks/privacypossum/commit/15db4394af5a79e05b41b750fc23db8aa5b1ac3d 

@MikeZeDev What installation of vbulletin was breaking?

@mazesy You are correct about this being a browser wide thing, currently, we inject anti-fingerprinting scripts in every frame. The solution would be to inject them into non-deactivated pages. I have some concerns about race conditions tho. I created a seperate issue for this, see #22.

**Comment by cowlicks** [comment]
Oh, just to be clear 15db439 makes the fingerprinting detection more robust to errors. The errors are what was breaking websites. It doesn't fix #22.

@MikeZeDev if the vbulletin site is still broken please re-open this issue.
