### ISSUE TITLE
Version 2019.7.9 breaking many sites

### ISSUE THREAD

**Issue by CollinChaffin** [cowlicks/privacypossum#184]
## Background

PrivacyPossum 2019.7.9

Chrome Version 77.0.3833.0 (Official Build) dev (64-bit)

## Issue Summary

Any links with referrals to Github, Reddit, and other major sites with PrivacyPossum v2019.7.9 enabled causes failures on those target sites.

## Issue Detail

As of this version (did not happen on last versions) to demonstrate this wide-spread issue and reproduce:

1. Log into Github (cookie saved)
2. Open new tab, perform Google search to a GH site result, follow and GH will indicate you are not logged in everything blocked. (Broken)
3. Click refresh and only then things are normal and you are logged in with no further failures

## Additional Information

The same occurs with Reddit and many other major sites since this update.  Reddit for instance not only performs a logout on referred link with PP enabled now, but also then of course looks (for most) vastly different if things like dark mode/themes/preferences/etc. are set on Reddit.  Like Github, to prove it is a PP issue, simply manually refresh or CTRL-refresh your referred tab, and low and behold (if redirected you may first have to click back then refresh) the refreshed page will suddenly indicate once again you are logged in but in case of Reddit also change appearance drastically. :)

This only happens with referred links since the update whereas first navigating to GH/reddit/others all subsequent activity seems to work albeit does indicate much more active blocks now on the PP icon which may or may not be related to this issue.

**Comment by CollinChaffin** [comment]
Surprised no update to this considering how much is broken since this extension updated.  Forced to disable it's so bad add other major sites that are NOT even via referral (directly opened) and fail like MS onenote.com (causes personal live ID login loop) etc.

Always liked this extension never major issues in the past so hopefully this radically new behavior isn't permanent gets reverted and I can eventually re-enable it.

**Comment by Elmar2001** [comment]
Yeah, this issue needs attention. I also noticed this when trying to login in using facebook to some websites. It would show error saying to restart the browser and whatnot, disabling PP solved this. Also, for me whitelisting (disabling in PP) DOESN'T WORK, I have to entirely disable the extension from extensions menu to unbreak the website.

**Comment by cowlicks** [comment]
@Elmar2001 @CollinChaffin Sorry for the inconvenience. I'll look into this tomorrow after work. In the meantime, pull requests are welcome.

**Comment by wjhir** [comment]
This seems to be affecting all sites, not just major ones. Opening any link to an external domain seems to have cookies removed from the request. Internal links work as expected. As mentioned, if the new website changes behavior based on missing cookies (e.g. redirects to a login page), the website becomes inconvenient (or impossible, apparently) to access.

**Comment by cowlicks** [comment]
@CollinChaffin @Elmar2001 @wjhir I've just published an update that should fix this. Sorry for the inconvenience and thank you for alerting me to this.
