### ISSUE TITLE
Breaks the search bar 

### ISSUE THREAD

**Issue by Philippe-Arnaud** [cowlicks/privacypossum#20]
Using DDGo, when the plug-in is active, even if it is disabled, the search is not working any more.
![image](https://user-images.githubusercontent.com/767823/39715676-62017184-522e-11e8-9668-4554b7d163be.png)

Disabling the extension makes the search work

If I search from the homepage of DDG, the link is not including the search string:
![image](https://user-images.githubusercontent.com/767823/39715812-baf0c2d6-522e-11e8-8ebc-ae2f30e1cf66.png)
_

**Comment by kioth** [comment]
Already reported [here](https://github.com/cowlicks/privacypossum/issues/11) 😉

**Comment by cowlicks** [comment]
@Philippe-Arnaud  thank you for your patience while we deal with the first big wave of installs Privacy Possum has gotten. I actually surprised that more didn't break.

I fixed a released a patch for this today in 15db439

I'll be adding selenium tests on Travis-ci soon so we can test for stuff like this automatically. See #7

If the new release did not fix this, feel free to re-open this issue.
