### ISSUE TITLE
There isn't a GitHub Pages site here

### ISSUE THREAD

**Issue by ediowar** [cowlicks/privacypossum#214]
valve.github.io/fingerprintjs2 in README.md

**Comment by PoorPocketsMcNewHold** [comment]
According to their repo, The main test of the fingerpintjs2 as moved there : https://fingerprintjs.com/demo

**Comment by ediowar** [comment]
When I reload the page [https://fingerprintjs.com/demo](https://fingerprintjs.com/demo) my fingerprint not change. The extension does not work?

**Comment by bbigras** [comment]
In my case a bot is not detected but my fingerprint doesn't change either.
