### ISSUE TITLE
raises entropy

### ISSUE THREAD

**Issue by KonoromiHimaries** [cowlicks/privacypossum#219]
If you are reporting a bug, then providing the following is helpful:
* browser name and version firefox latest
* privacy possum version latest

https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions#small_orange_diamond-dont-bother

**Comment by cowlicks** [comment]
Thanks for the article. The threat model they have for fingerprinting is different from the one privacy possum has.
