### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by bbigras** [cowlicks/privacypossum#222]
I hope it doesn't sound rude.

I'm just wondering if the author is still interested in this great extension or if the community should step in.

We all have busy lives and life is short. There's nothing wrong with having other priorities.

**Comment by ltGuillaume** [comment]
My thoughts exactly... @cowlicks

**Comment by mkrupczak3** [comment]
@cowlicks bump

**Comment by mkrupczak3** [comment]
To be frank, I have trouble keeping up nowadays with best practices for privacy extensions, blockers, etc.

I read cowlicks description and thought there was a gain to be had of possum over badger, but IDK since badger has had more recent updates.

**Comment by mds08011** [comment]
The developer addressed this in the Firefox Extension release notes:
> Release notes for 2019.7.18
First update in a while! Sorry, having a full-time job does that. I welcome all the help I can get at https://github.com/cowlicks/privacypossum
>
> I'm always happy to help folk contribute at any skill level. There is always some way to help.
>
> This is mostly a release that improves testing and developer workflow stuff, which should help me make more frequent releases in the future.
>
> There are also several minor bugfixes and updates.

**Comment by meow81** [comment]
despite that communication, an unmaintained extension with site compatibility issues piling up is becoming less useful.  I'm uninstalling and going back to privacy badger.

**Comment by tylerwolf35** [comment]
@cowlicks Would you still recommend this extension over Privacy Badger, it appears to be unmaintained whereas Privacy Badger is being actively updated.

**Comment by mkrupczak3** [comment]
@cowlicks ^^^
I really like the idea of the extension laid out in the readme, but for something like this I think up-to-date maintenance is key.

Both for my own use and for recommending readers of the blog I run, I'd like to know what to recommend people use.

**Comment by tylerwolf35** [comment]
@mkrupczak3 Agreed, I have since switched to Privacy Badger but would gladly switch back given more information on the maintenance status of the project.

**Comment by ghostwords** [comment]
[Privacy Badger and Privacy Possum are different animals](https://www.reddit.com/r/privacy/comments/9lanyg/privacy_possum_or_privacy_badger_and_whyhow/e78a0ii/), one is not a replacement for the other.

**Comment by jasonbrown1965** [comment]
. . .

Crowd sourcing taken a big dive lately.
Makes me wonder how many other great apps like this one are left hanging?
Especially if as @ghostwords links ^ they both serve purposes.
**OpenQuery:** If we then use Badger and Possum at the same time, will the more up-to-date Badger block front-and-centre attacks, while Possum skirmishes out among wider, longer-term threats? Or, less positively, will the two conflict ?

. . .

**Comment by Forbo** [comment]
It looks like there's been some work on some commits as of May 20, 2020:
https://github.com/cowlicks/privacypossum/pull/237
https://github.com/cowlicks/privacypossum/commits/design-from-firefox

**Comment by mkrupczak3** [comment]
Cool! I'll keep track of this. 

For now though, I'm just recommending Privacy Badger instead of Possum, until I know what the fate of this project will be.

**Comment by ltGuillaume** [comment]
Those changes are just cosmetics and don't address any of the issues listed here. It's beyond me how the add-on in its current state, no matter how great its potential might be, was selected to be among the few add-ons the new Firefox for Android currently supports.

**Comment by mkrupczak3** [comment]
@ltGuillaume What's the skinny on this "new" Firefox for Android?

**Comment by ltGuillaume** [comment]
> @ltGuillaume What's the skinny on this "new" Firefox for Android?

https://www.ghacks.net/2020/07/29/firefox-for-android-migration-begins-for-stable-channel-users/

**Comment by mkrupczak3** [comment]
@ItGuillaume Sad to see. Mozilla has made some headscratcher decisions lately.

I hope that they know what they're doing for the long term though. Their re-write of the rendering engine for Firefox in Rustlang was pretty darn impressive. 

Are there any benefits to Fenix currently? Should I switch to it from my current version of Firefox for android? (I've been using a mix of Firefox for Android and the Chromium-esque "Kiwi browser" on mobile for now, just becuase the chrome engine is so much faster on mobile)

**Comment by ltGuillaume** [comment]
If you don't use any extensions other than the 9 that are now available (uBlock and Decentraleyes being the most important) and if you don't use any about:config tweaks, then you're good to go and should try Fenix. Some have had great results in terms of speed and reliability (I can't complain), some have had the worst experience with it, ever.

**Comment by mkrupczak3** [comment]
Huh. Couldn't hurt. 

I should just install Firefox Nightly then as a different app?

**Comment by ltGuillaume** [comment]
Stable, Beta and Nightly are all Fenix now. You can still get Fennec from F-Droid.

**Comment by cowlicks** [comment]
Hi, currently, I'm the only person maintaining this project in my free time. Pull requests welcome.

**Comment by unbeatable-101** [comment]
@cowlicks just wondering, I saw that you removed the cookies permission in a recent commit, and I don't see the permission in about:addons, how did you update it without uploading to AMO?
