### ISSUE TITLE
Privacy possum is not available on Android after the new update

### ISSUE THREAD

**Issue by kioth** [cowlicks/privacypossum#27]
Privacy possum is not available on Android after the new update. I'm not sure if it was intentional or unintentional. Since this change is not mentioned in release notes, I am assuming this is unintentional.

**Comment by cowlicks** [comment]
It was intentional because I hadn't tested on android. See my [comment](https://github.com/cowlicks/privacypossum/issues/29#issuecomment-387504091) on #29. 

Was it working ok for you? Did the popup work?

**Comment by cowlicks** [comment]
closing in favor of #29

**Comment by kioth** [comment]
@cowlicks yes, it was working. Everything was working except duckduckgo didn't work just like on non-mobile firefox.
