### ISSUE TITLE
Referer head seemingly not blocked

### ISSUE THREAD

**Issue by QuentinMoss** [cowlicks/privacypossum#281]
If you are reporting a bug, then providing the following is helpful:
* Firefox 84.0.1
* privacy possum version: 2019.7.18

Was testing out tenta's browser tool and noticed that privacy possum was reporting that it blocked referer, but it doesn't appear to be working. See below.

<img width="1381" alt="Screen Shot 2020-12-28 at 7 42 38 PM" src="https://user-images.githubusercontent.com/350409/103257336-a1bcad00-4945-11eb-986e-453cf59738d7.png">

**Comment by jlardilagon** [comment]
Same issue while browsing MS Store, google gmail and many other pages

Firefox 84.0.2
privacy possum version: 2019.7.18
OS Win10

**Comment by QuentinMoss** [comment]
@jlardila Judging by the activity i would not recommend relying on this extension.

**Comment by Snaxeko** [comment]
It only blocks referer for third parties, it would break too many websites to block referer for 1st party. But you're right, anyway this project is discontinued.
