### ISSUE TITLE
Support for Firefox android

### ISSUE THREAD

**Issue by killoid** [cowlicks/privacypossum#29]
currently i can't install it on my firefox for android. so, firefox android support would be great.

**Comment by jawz101** [comment]
I have it installed

**Comment by jawz101** [comment]
Oops.  I guess it's that the addon store now says it's not compatible

**Comment by killoid** [comment]
yes, the addon store says it's incompatible.

**Comment by cowlicks** [comment]
I had previously marked the the extension as compatible for all platforms, but I hadn't actually tested it on mobile. With the recent attention I was weary about fielding issues and supporting a platform I hadn't actually tested on so I removed mobile support.

Mobile support is not hard, but I don't know how hi priority it is either. If folks wanna "vote" for  it feel free to give this issue a :+1:

**Comment by ruiumbelino** [comment]
+1

**Comment by cowlicks** [comment]
I've re-enabled privacy possum for android in today's release. This is totally untested.

Feel free to make bug reports for android when you see them: @krathalan @sniperle @ruiumbelino @grenzor @kioth @j0shimi 

Or even better make a pull request :)

**Comment by jawz101** [comment]
I used to have a cowlick when I had hair.
