### ISSUE TITLE
Threat model

### ISSUE THREAD

**Issue by KOLANICH** [cowlicks/privacypossum#32]
>When considering some anti-tracking measure we do not ask "Is it possible to circumvent this?". Instead we ask "Is it cost-effective for a tracking company to circumvent this?". If the answer is "yes, no" we accept it.

All threat models are about it. It is not impossible to break RSA. One just needs to wait for a quantum computer being available to him. It's not impossible to break SHA-256. You only need to hire top researchers and pay them enough for enough time. Or you can wait until someone else developed the thing. It is not impossible to track every user in the Internet. One just needs to reduce the users only to the ones who explicitly allow and help tracking themselves. It is not impossible to block Tor in China. In North Korea it is successfuly blocked.

So what you have already sounds like a threat model `an adversary can do everything we consider "effiicient"`. So I guess you should change the paragraph.

**Comment by cowlicks** [comment]
Hello @KOLANICH you are correct, that is something like a threat model, however at this time I would like to avoid creating an explicit threat model for for Privacy Possum. I think the idea of a threat model
