### ISSUE TITLE
blocking fingerprinting breaks twitch.tv

### ISSUE THREAD

**Issue by xevrem** [cowlicks/privacypossum#33]
blocking fingerprinting on twitch.tv prevents the page from finishing its load... page is React-based, so perhaps switch to corrupting the fingerprint instead of a full block?

Note: using Firefox Dev Edition 61

**Comment by j0shimi** [comment]
I can also confirm using standard 6.0 build of Firefox, Twitch is broken with Fingerprinting enabled.

**Comment by cowlicks** [comment]
hi @xevrem @j0shimi thank you! PP should have defaulted to corrupting the fp instead of a block, but I hadn't added "twitchcdn.net" to the multidomain first party list with "twitch.tv". I'll do this now. Thanks!
  
Also, just FYI Twitch **really is fingerprinting**
