### ISSUE TITLE
PP does not work on Google Docs

### ISSUE THREAD

**Issue by b-meson** [cowlicks/privacypossum#34]
For some reason, using Google Docs will refuse to load when using Privacy Possum on the latest Firefox (Quantum) on OS X.

**Comment by cowlicks** [comment]
:wave: I'm having trouble reproducing this. What version of privacy possum is it? There was a similar bug in a previous version. Are there any tracebacks in the console?

I made #36 to track making it easier to get debugging information for bug reports.

**Comment by cowlicks** [comment]
Closing for lack of info. @b-meson if this is still an issue feel free to reopen.
