### ISSUE TITLE
Expose debug log for reporting issues 

### ISSUE THREAD

**Issue by cowlicks** [cowlicks/privacypossum#36]
It should be easy to access the debug log, like from the popup, so people can report issues with it.

**Comment by b-meson** [comment]
Hi @cowlicks I don't see a corresponding documentation change for this PR :thinking:

**Comment by cowlicks** [comment]
@b-meson I've added an issue template that explains how to access the debug log. However I need to make a release for the debug log changes to go out. I'll do that in the next hour or so.

**Comment by cowlicks** [comment]
@b-meson new release has been pushed to both Chrome and FF.

I left accessing the debug log as a manual process oriented toward developers. I did this for two reasons:
* the debug log contains urls and etags, which I would not want privacy conscious users to share accidentally. I'd like to keep the debug log hidden until I can redact this info easily.
* I'm not sure what a good work flow for and end user would look like yet.
