### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by paul1149** [cowlicks/privacypossum#38]
I don't know if this is something I did or not, but it looks like the PP icon has gone dark, and that nothing is being done. For instance, suddenly I remain logged into Disqus on every site.

On one site I unchecked the three rules showing on the drop-down menu, but now I can't see the rules in order to enable them again. Something is wacked.

Otherwise, I was really liking the way it was working.

Same situation on both Vivaldi and Slimjet.

**Comment by cowlicks** [comment]
Hello @paul1149 what browser and  privacy possum version are you on?

**Comment by cowlicks** [comment]
Also a screenshot of what you are describing would be helpful. #36 would help with stuff like this.

**Comment by paul1149** [comment]
Hi,
I'm primarily on Vivaldi snapshot 1.16.1177.5 (Chrome/65.0.3325.183) , PP 2018.5.10.

I also use Slimjet, Version 18.0.5.0 (based on Chromium 64.0.3282.119) (Official Build) (64-bit), PP 2018.5.7.

I'm on MX Linux 17.1 x64.

**Comment by paul1149** [comment]
Here are a couple of shots:
![possum](https://user-images.githubusercontent.com/13952246/39901252-554a16da-5495-11e8-8f8a-7ec075233ae0.jpg)
![possum2](https://user-images.githubusercontent.com/13952246/39901253-555817b2-5495-11e8-8cb2-e5e8faddd1e5.jpg)

**Comment by cowlicks** [comment]
![screenshot_20180510-234655_chrome](https://user-images.githubusercontent.com/598099/39910562-b5bb8b54-54ac-11e8-992a-ceebde056b4d.jpg)
I also got this report on the chrome store that may be related. 

I honestly have no clue what is going on here. If you right click  and inspect the pop-up, does the console show any errors? If you can inspect, the background of the extension can you are any errors there? (I can explain how to do this later when I'm not posting from my phone).

**Comment by cowlicks** [comment]
Didn't mean to close, sorry

**Comment by paul1149** [comment]
Today it's working on Slimjet. I suppose that's a function of the ext. updating to 2018.5.10. Vivaldi still not working.

**Comment by Mioni** [comment]
Same here.
This update not working on Vivaldi.

**Comment by cowlicks** [comment]
Ah, I reproduced this in Chrome finally. I'll figure out what is going on ASAP.
```

**Comment by cowlicks** [comment]
Ah I think we are hitting the 100Kb limit. We need to switch to `chrome.storage.localstorage` and need to be more conservative with disk usage.

**Comment by cowlicks** [comment]
#52 is merged, which should fix this. I'll make a release tomorrow. My guess is that y'all saw an error with Vivaldi because it sets `chrome.storage.BYTES_QUOTA` to something lower.

Thanks for your patience in this.

**Comment by paul1149** [comment]
Good work. Thanks.
