### ISSUE TITLE
Request: releases change log

### ISSUE THREAD

**Issue by ruiumbelino** [cowlicks/privacypossum#39]
It's possible to have a change log, about the new versions, under Release tab, when you find it more stable?

https://github.com/cowlicks/privacypossum/releases

Thanks

**Comment by cowlicks** [comment]
Hi @ruiumbelino I have been tagging releases, but I hadn't pushed them to github until now. Thanks for reminding me! The releases are now available at the link you provided.

I'll try to keep a more complete changelog moving forward. Thanks!

**Comment by ruiumbelino** [comment]
Hi @cowlicks ,

Can you add some description about what was changed, like for example uBlock Origin does?

Thanks
