### ISSUE TITLE
make browser icon more visible with dark browser themes

### ISSUE THREAD

**Issue by Decopi** [cowlicks/privacypossum#46]
Hi @cowlicks !

It is very nice to see PrivacyPossum growing, with almost 600 users at Firefox. Congrats!

I have a simple request, without urgency/priority: Please, consider the possibility to change the PP' icon black color, with another color, blue, green, yellow, orange etc, which will contrast on browser black themes.

Thanks a lot!!

PS: The PP' counter color is "ok". No changes needed.

**Comment by cowlicks** [comment]
It would probably be easier, and look better, to just give the possum icon a background color instead of having it be transparent like it currently is.

**Comment by CollinChaffin** [comment]
Not intending to annoy but this has been open for a while and I hadn't seen a post to show the team the extent to which the PP icon really is totally invisible in a dark theme.  Here is a screenshot of it next to the uBlock icon if it helps (I think it actually was even auto-adjusted brighter in the screenshot app as it appears even more invisible in reality but you get the idea):

![snag_11-4-2018_17-42-53a](https://user-images.githubusercontent.com/9301483/47971858-9fc07180-e08d-11e8-9126-d71753de9538.png)


Thanks for providing such an awesome extension!

**Comment by cowlicks** [comment]
@CollinChaffin fixed on master. I'll be making a release as soon as possible.
