### ISSUE TITLE
kissanime keeps auto disabling the extension 

### ISSUE THREAD

**Issue by sumshttyusernameidk** [cowlicks/privacypossum#55]
firefox 59.0.3

pp "2018.5.17"

was fine at first but a pop message appeared saying if i want to upgrade to preimum and i clicked on the no i want to continue seeing ads option

update: i closed firefox, reopened it and tried seeing if that fixed it and it did. also there might be two kissanime sites? the one i use is https://kissanime.ac/kissanime.html

**Comment by cowlicks** [comment]
@sumshttyusernameidk hello, can you elaborate more on what you mean by "disabling the extension"? It it being completely deactivated? A screenshot might be helpful.

**Comment by cowlicks** [comment]
Closing for lack of info. @sumshttyusernameidk  if this is still an issue, please re-open.
