### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by krathalan** [cowlicks/privacypossum#62]
It would be nice if Privacy Possum had an official privacy policy on `https://addons.mozilla.org`. Given the nature of the addon and the fact that it's free and open source, I'm assuming the addon does not collect and/or send data to any server.

I even wrote a policy for you if you'd like to copy/paste it:
Privacy Possum does not collect or send data to any server.

**Comment by cowlicks** [comment]
Thank you @krathalan ! Would you like to make a PR for that? I can add it to the Mozilla listing in the next release.

**Comment by krathalan** [comment]
Done. https://github.com/cowlicks/privacypossum/pull/65

**Comment by cowlicks** [comment]
closed  by #65

**Comment by cowlicks** [comment]
@krathalan it is now live on the Mozilla listing. Thanks! https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/privacy/

I saw no such field for the chrome listing.
