### ISSUE TITLE
Request: Basilisk support

### ISSUE THREAD

**Issue by FrostKnight** [cowlicks/privacypossum#78]
Basilisk is like the web browser firefox, but it uses XUL instead of Webext.  I was wondering if there would be anything, that would convince you to support basilisk indefinitely, even if the addon is on your website, etc...

I absolutely love this addon, and I appreciate your kind work, I only wish more people knew about this addon, in the free software community. It blows privacy badger out of the water, and then some. Privacy badger should be ditched in favor of this addon. :)
But anyways, that is my wish. Once ESR switches to webext things get worse for firefox. 

I hope this is a good place for my request.

**Comment by cowlicks** [comment]
Hi @FrostKnight I'd like to support as many browsers as possible, but I need help from regular users of the browsers. These are the steps I'd follow to start supporting basilisk, or any new browser:
* Install the browser
* Install the development version of Privacy Possum from source, instructions for how to do this with [Firefox are here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) (probably a similar process to basilisk) and [Chrome are here](https://www.mattcutts.com/blog/how-to-install-a-chrome-extension-from-github/)
* Go to a some sites with known tracking, like twitch.tv, http://valve.github.io/fingerprintjs2/ and see if the extension behaves normally.
* If everything is normal, start distributing it on that browser
* if not, start debugging

You probably already have done the first step, so you might be able to get through these steps more quickly than me. If you're able to do this initial testing, it would help me out a lot.

Thank you!

**Comment by FrostKnight** [comment]
My distro doesn't currently use it, but it is in development of forking it to remove non-libre stuff.   But yeah, it works on normal basilisk very well so far. 

Anywho though,  it is similiar to Firefox esr 52. But yeah, I am very much willing to do so.  

You are a kind soul, I have given you a review on mozilla's website. Although you may not know this, but I was using it with firefox esr 52 at the time.

Quick question though,  have you reached out to EFF and suggested they ditch privacy badger in favor of privacy possum? If you have, and they said no, then they are foolish.

**Comment by FrostKnight** [comment]
I am getting frustrated a bit by mozilla accounts, is it possible that you could make there another way to download the development version? If so, I will gladly try it out for you.

**Comment by cowlicks** [comment]
Hi @FrostKnight I look forward to seeing your tests with Basilisk. You can download privacy possum's source from github by running:
`git clone https://github.com/cowlicks/privacypossum.git`

**Comment by FrostKnight** [comment]
Thanks, I should add the palemoon devs mentioned something in their forum if you wanted to make sure it was compatible. Would this be possible?

"WebExtensions MUST have an extension ID if they are going to be compatible with UXP. It takes little effort on the extension dev's side to do so and saves us an architectural nightmare.

The extension dev can solve this by adding an ID."

They seem to say this would be enough.

That aside, tell me something,  how do I make the, xpi? I made the zip, what is the next step? I tried to load the zip, but it didn't work with temporary load.

**Comment by FrostKnight** [comment]
(firefox:3643): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
1531099317802	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no] 

is the error I got when I  followed your steps.  Might be an error that can be fixed, 

I had a thought though, I am going to link your addon to my friends from Hyperbola, maybe they can make this work. But yeah, you may need to have an extension ID to be compatible with UXP. I don't know, but just try okay?

**Comment by FrostKnight** [comment]
I have a bad feeling that it might need to be rewritten with only legacy code to make it work... I don't really know why.

**Comment by cowlicks** [comment]
@FrostKnight I'm afraid rewriting Privacy Possum to use legacy/XUL apis would be **a lot** of work. I've never written an XUL addon, and the API's are quite different from my understanding. So this is not a priority for me at this time.

If you are interested in trying to do this yourself, here is the approach I would take; All of the WebExtension API's are shimmed in `src/js/shim.js` if you could write wrappers for the XUL apis to look like WebExtension apis, you could insert those functions there. Then if your wrappers worked well, the extension should work.

**Comment by FrostKnight** [comment]
Okay, then I guess I can close for the time being or until you find time, or feel like doing it, just know, that I, and other people would love this.  I might do this if I could gain enough experience, but I have zero experience.  Whatsoever so yeah, thanks for the offer, but for the time being, just keep Firefox esr 52+ support if possible. Basilisk I think might support it, but sadly, I cannot use it.  Maybe if someone approaches you or someone you know would be willing, but till then, I guess it won't happen. Thanks though for being willing to at least support firefox esr 52+.  
PS, if you at any point you change your mind, I will gladly try it out.
