### ISSUE TITLE
breaks microsoft live mail

### ISSUE THREAD

**Issue by Jon-guy30** [cowlicks/privacypossum#90]
Hi, some time ago this website https://login.live.com stopped working. When I disable PP it works again. 

When I try to login it says "something went wrong :-(" and I can't login. Something must have changed a few days ago, because it worked before. They probably updated the website.

**Comment by cowlicks** [comment]
Hi @Jon-guy30 what browser are you using? I'm not able to reproduce this on Chrome 68. If you know how to open the javascript console on the page, can you check for any errors there?

**Comment by Jon-guy30** [comment]
I'm using firefox 61.0.2. I'm suspecting this addon because when I disable it through about:addons I'm able to login, but when I have it enabled I cannot login. 

It might just be my configuration. I've changed it quite a bit, wouldn't surprise me if something was broken on my end. 

<details>
  <summary>JS console output</summary>

Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:1

Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:7

Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2

1533898534947	addons.webextension.woop-NoopscooPsnSXQ@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.

1533898534947	addons.webextension.{d1b9b4a8-eba2-44b3-be23-2cfad98fde22}	WARN	Please specify whether you want browser_style or not in your browser_action options.

1533898534948	addons.webextension.MiningBlocker@MiningBlockerAddOn.com	WARN	Please specify whether you want browser_style or not in your browser_action options.

1533898534948	addons.webextension.https-everywhere@eff.org	WARN	Please specify whether you want browser_style or not in your browser_action options.

1533898534948	addons.webextension.jid1-CKHySAadH4nL6Q@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.

1533898534949	addons.webextension.{b6840179-45a1-4a2d-a4ef-e2815c1faa28}	WARN	Please specify whether you want browser_style or not in your browser_action options.

[Show/hide message details.] win.gBrowser is undefined CustomizableWidgets.jsm:365
	onCreated
resource:///modules/CustomizableWidgets.jsm:365:11
wrapWidgetEventHandler/aWidget[aEventName]
resource:///modules/CustomizableUI.jsm:2516:16
buildWidget
resource:///modules/CustomizableUI.jsm:1521:9
getWidgetNode
resource:///modules/CustomizableUI.jsm:986:16
buildArea
resource:///modules/CustomizableUI.jsm:816:32
registerToolbarNode
resource:///modules/CustomizableUI.jsm:764:9
registerToolbarNode
resource:///modules/CustomizableUI.jsm:3160:5
toolbar_XBL_Constructor
chrome://browser/content/customizableui/toolbar.xml:45:11
next self-hosted:570:9 toolbar_XBL_Constructor
chrome://browser/content/customizableui/toolbar.xml:31:13
next self-hosted:570:9 toolbar_XBL_Constructor
chrome://browser/content/customizableui/toolbar.xml:31:13
update
chrome://browser/content/tabbrowser.js:4721:19
onBeforeInitialXULLayout
chrome://browser/content/browser.js:1185:5
<anonymous>
chrome://browser/content/browser.js:1145:5

Error: Could not establish connection. Receiving end does not exist. injected-event-bridge.js:14:7

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ background.js:18:4

Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-CJS-1.2.0&x-apikey=3b1ea01450be48f29759d868931e225d-7167685b-f6ff-421c-aa64-8ae16fe92128-7283. (Reason: CORS request did not succeed).

XML Parsing Error: no root element found
Location: https://outlook.live.com/mail/bootr.ashx?bret=fail&cId=CC47DD01EB5B461AA3C54BD7A2B57A01&csev=HE1PR09MB0650&dag=EURPR09DG041&fost=eurprd09&dring=WW&app=Mail&cver=20180730.02&csver=18.7.20.2&fe=HE1PR0401CA0051&be=HE1PR09MB0650&cbe=HE1PR09MB0650.EURPRD09.PROD.OUTLOOK.COM&wsver=15.20.1038.21&te=1&puid=0003BFFDCC4EAA79&tid=84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa&mbx=0003bffd-cc4e-aa79-0000-000000000000&prem=0&br=1&ns=0&nt=0&redc=0&pe=900&pltnonav=1100&esrc=Bootstrap&et=ClientError&err=TypeError%3A%20this.adjusted%20is%20undefined
Line Number 1, Column 1:
</details>

**Comment by ltGuillaume** [comment]
Confirmed on Waterfox 56.2.2.

Web Console output:
> downloadable font: VDMX: misaligned table (font-family: "wf_segoe-ui_semilight" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-semilight.ttf  unknown:18:19
downloadable font: rejected by sanitizer (font-family: "wf_segoe-ui_semilight" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-semilight.ttf  unknown:18:19
downloadable font: LTSH: invalid table offset (font-family: "wf_segoe-ui_normal" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-regular.ttf  unknown:12:19
downloadable font: rejected by sanitizer (font-family: "wf_segoe-ui_normal" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-regular.ttf  unknown:12:19

Browser console output:
>unsafe/forbidden CPOW usage  browser.js:71:4
Error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data  owa.mail.js:50:248057
Error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data  owa.mail.js:50:248057
"Navigation error
      tabId: 200
      url: https://outlook.live.com/mail/inbox?bO=2
      error: Error code 2152398850"  utils.js:188
downloadable font: LTSH: invalid table offset (font-family: "wf_segoe-ui_normal" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-regular.ttf  unknown:12:19
downloadable font: rejected by sanitizer (font-family: "wf_segoe-ui_normal" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-regular.ttf  unknown:12:19
downloadable font: VDMX: misaligned table (font-family: "wf_segoe-ui_semilight" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-semilight.ttf  unknown:18:19
downloadable font: rejected by sanitizer (font-family: "wf_segoe-ui_semilight" style:normal weight:normal stretch:normal src index:1) source: https://outlook.live.com/owa/auth/15.20.1059/themes/resources/segoeui-semilight.ttf  unknown:18:19

**Comment by ltGuillaume** [comment]
Confirmed working! Thanks! :-)

**Comment by Jon-guy30** [comment]
I can login once more! Hurray!

Don't worry, I see you've been busy, one month is reasonable. ;)
