### ISSUE TITLE
PP is now off

### ISSUE THREAD

**Issue by dacq11** [cowlicks/privacypossum#95]
On firefox 57 PP was on for every Web site I visited. I've switched to 61 and now PP switches off after each Web site has loaded (it's enabled in FF's addon section). I want it on.

PP downloaded on 8 Aug 2018.

**Comment by cowlicks** [comment]
Hi @dacq11 thank you for the report. I'm not able to reproduce this problem and I'm not sure what is causing it. Can you try reinstalling the addon? You can do this by going to `about:addons` and clicking "remove", then go to the [listing](https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/) and install it again.

Please let me know if this works

**Comment by dacq11** [comment]
I've reinstalled it but there's no image on the icon button. If I press it a tiny box appears below it.

Thx.
